[2020-11-08 00:59:41,606] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 01:00:10,950] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\urls.py changed, reloading.
[2020-11-08 01:00:12,144] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 01:01:52,830] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\urls.py changed, reloading.
[2020-11-08 01:01:54,022] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 01:03:02,158] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\urls.py changed, reloading.
[2020-11-08 01:03:03,361] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 01:03:37,643] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head HTTP/1.1" 301 0
[2020-11-08 01:03:38,125] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /head_content/head/
Traceback (most recent call last):
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\mixins.py", line 42, in list
    serializer = self.get_serializer(page, many=True)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
TypeError: 'ListSerializer' object is not callable
[2020-11-08 01:03:38,129] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /head_content/head/ HTTP/1.1" 500 110907
[2020-11-08 01:03:38,161] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-11-08 01:03:38,161] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2294
[2020-11-08 01:04:29,175] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 01:04:30,308] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 01:04:33,110] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /head_content/head/
Traceback (most recent call last):
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\mixins.py", line 42, in list
    serializer = self.get_serializer(page, many=True)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
TypeError: 'HeadContentSerializer' object is not callable
[2020-11-08 01:04:33,115] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /head_content/head/ HTTP/1.1" 500 111086
[2020-11-08 01:06:20,639] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\serializers.py changed, reloading.
[2020-11-08 01:06:21,823] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 01:06:42,358] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\serializers.py changed, reloading.
[2020-11-08 01:06:43,650] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 01:06:50,325] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /head_content/head/
Traceback (most recent call last):
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\mixins.py", line 42, in list
    serializer = self.get_serializer(page, many=True)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
TypeError: 'HeadContentSerializer' object is not callable
[2020-11-08 01:06:50,330] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /head_content/head/ HTTP/1.1" 500 111351
[2020-11-08 01:06:50,350] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-11-08 01:06:56,533] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /head_content/head/
Traceback (most recent call last):
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\generics.py", line 239, in get
    return self.list(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\mixins.py", line 42, in list
    serializer = self.get_serializer(page, many=True)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\generics.py", line 110, in get_serializer
    return serializer_class(*args, **kwargs)
TypeError: 'HeadContentSerializer' object is not callable
[2020-11-08 01:06:56,536] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /head_content/head/ HTTP/1.1" 500 111351
[2020-11-08 01:06:56,574] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-11-08 01:09:03,919] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 01:09:05,092] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 01:09:09,150] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/ HTTP/1.1" 200 15117
[2020-11-08 01:09:09,180] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[2020-11-08 01:09:09,181] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[2020-11-08 01:09:09,183] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[2020-11-08 01:09:09,183] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[2020-11-08 01:09:09,185] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[2020-11-08 01:09:09,186] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[2020-11-08 01:09:09,192] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[2020-11-08 01:09:09,192] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[2020-11-08 01:09:09,193] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[2020-11-08 01:09:09,194] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[2020-11-08 01:09:09,201] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[2020-11-08 01:09:09,252] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-11-08 01:09:45,515] [log.py:228] [log:log_response] [WARNING]- Bad Request: /head_content/head/
[2020-11-08 01:09:45,515] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /head_content/head/ HTTP/1.1" 400 15144
[2020-11-08 01:09:52,780] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/ HTTP/1.1" 200 15117
[2020-11-08 01:09:52,801] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2020-11-08 01:09:52,801] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2020-11-08 01:09:52,801] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2020-11-08 01:09:52,801] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-11-08 01:09:52,805] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 01:09:52,805] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 01:10:22,799] [log.py:228] [log:log_response] [WARNING]- Bad Request: /head_content/head/
[2020-11-08 01:10:22,799] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /head_content/head/ HTTP/1.1" 400 15144
[2020-11-08 01:14:20,194] [log.py:228] [log:log_response] [WARNING]- Bad Request: /head_content/head/
[2020-11-08 01:14:20,195] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /head_content/head/ HTTP/1.1" 400 15144
[2020-11-08 01:16:10,084] [log.py:228] [log:log_response] [WARNING]- Bad Request: /head_content/head/
[2020-11-08 01:16:10,085] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /head_content/head/ HTTP/1.1" 400 16155
[2020-11-08 08:36:33,039] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\models.py changed, reloading.
[2020-11-08 08:36:34,267] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 08:37:00,634] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 08:37:35,922] [log.py:228] [log:log_response] [WARNING]- Bad Request: /head_content/head/
[2020-11-08 08:37:35,923] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /head_content/head/ HTTP/1.1" 400 16157
[2020-11-08 08:38:54,013] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\models.py changed, reloading.
[2020-11-08 08:38:55,182] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 08:39:17,391] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 08:39:39,353] [log.py:228] [log:log_response] [WARNING]- Bad Request: /head_content/head/
[2020-11-08 08:39:39,354] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /head_content/head/ HTTP/1.1" 400 15808
[2020-11-08 08:40:19,584] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\models.py changed, reloading.
[2020-11-08 08:40:20,752] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 08:40:25,428] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\models.py changed, reloading.
[2020-11-08 08:40:26,579] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 08:40:46,107] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 08:41:10,262] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 16451
[2020-11-08 08:42:51,281] [log.py:228] [log:log_response] [WARNING]- Bad Request: /head_content/head/
[2020-11-08 08:42:51,282] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /head_content/head/ HTTP/1.1" 400 15844
[2020-11-08 08:43:11,612] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\models.py changed, reloading.
[2020-11-08 08:43:12,792] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 08:43:33,170] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 08:43:45,802] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 16523
[2020-11-08 08:44:16,471] [log.py:228] [log:log_response] [WARNING]- Bad Request: /head_content/head/
[2020-11-08 08:44:16,472] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /head_content/head/ HTTP/1.1" 400 15110
[2020-11-08 08:45:24,651] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 16595
[2020-11-08 08:50:32,085] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 15819
[2020-11-08 08:51:01,585] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 16499
[2020-11-08 08:51:29,190] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 16645
[2020-11-08 08:51:57,741] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 16473
[2020-11-08 08:52:31,785] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 17049
[2020-11-08 08:57:34,807] [log.py:228] [log:log_response] [WARNING]- Bad Request: /head_content/head/
[2020-11-08 08:57:34,808] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /head_content/head/ HTTP/1.1" 400 15483
[2020-11-08 08:58:35,899] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 15909
[2020-11-08 08:58:54,917] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 16462
[2020-11-08 08:59:06,503] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 16488
[2020-11-08 08:59:21,158] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 16536
[2020-11-08 08:59:38,441] [log.py:228] [log:log_response] [WARNING]- Bad Request: /head_content/head/
[2020-11-08 08:59:38,441] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /head_content/head/ HTTP/1.1" 400 15107
[2020-11-08 09:00:01,890] [log.py:228] [log:log_response] [WARNING]- Bad Request: /head_content/head/
[2020-11-08 09:00:01,890] [basehttp.py:157] [basehttp:log_message] [WARNING]- "POST /head_content/head/ HTTP/1.1" 400 15740
[2020-11-08 09:00:23,788] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 16448
[2020-11-08 09:00:55,720] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 16430
[2020-11-08 09:01:06,193] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 16506
[2020-11-08 09:01:21,592] [basehttp.py:157] [basehttp:log_message] [INFO]- "POST /head_content/head/ HTTP/1.1" 201 16500
[2020-11-08 09:01:31,016] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/ HTTP/1.1" 200 25469
[2020-11-08 09:10:22,378] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/ HTTP/1.1" 200 25469
[2020-11-08 09:10:22,412] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2020-11-08 09:10:22,413] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-11-08 09:10:22,413] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2020-11-08 09:10:22,413] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2020-11-08 09:10:22,414] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 09:10:22,414] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 09:10:50,992] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:10:56,279] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?type=guess&geohash=28.227779%2C112.938858 HTTP/1.1" 200 6757
[2020-11-08 09:13:46,588] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:21:04,592] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:21:53,135] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 09:21:54,359] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:23:35,438] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:23:37,918] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 200 24925
[2020-11-08 09:23:37,936] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[2020-11-08 09:23:37,943] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2020-11-08 09:23:37,943] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[2020-11-08 09:23:37,944] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[2020-11-08 09:23:37,946] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[2020-11-08 09:23:37,948] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-11-08 09:23:37,948] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2020-11-08 09:23:37,949] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2020-11-08 09:23:37,949] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 09:23:37,950] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 09:23:37,964] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[2020-11-08 09:25:26,501] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:25:32,690] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 09:25:34,010] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:25:52,338] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:25:55,282] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 200 24925
[2020-11-08 09:25:55,308] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2020-11-08 09:25:55,314] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2020-11-08 09:25:55,314] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 09:25:55,317] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2020-11-08 09:25:55,318] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 09:25:55,318] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-11-08 09:29:20,330] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:29:56,198] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 09:29:57,403] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:30:00,180] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /head_content/head/
Traceback (most recent call last):
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\djangos\mysite\apps\head_tabar\views.py", line 14, in list
    queryset = Head_content.objects.filter({"is_in_serving":1})
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1350, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1381, in _add_q
    check_filterable=check_filterable,
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1236, in build_filter
    raise FieldError("Cannot parse keyword query as dict")
django.core.exceptions.FieldError: Cannot parse keyword query as dict
[2020-11-08 09:30:00,185] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 500 132906
[2020-11-08 09:30:00,213] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-11-08 09:30:12,922] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 09:30:14,128] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:30:15,280] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /head_content/head/
Traceback (most recent call last):
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\djangos\mysite\apps\head_tabar\views.py", line 14, in list
    queryset = Head_content.objects.filter({"is_in_serving":1})[0]
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1350, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1381, in _add_q
    check_filterable=check_filterable,
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1236, in build_filter
    raise FieldError("Cannot parse keyword query as dict")
django.core.exceptions.FieldError: Cannot parse keyword query as dict
[2020-11-08 09:30:15,285] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 500 132912
[2020-11-08 09:30:42,227] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 09:30:43,435] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:30:45,151] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /head_content/head/
Traceback (most recent call last):
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\djangos\mysite\apps\head_tabar\views.py", line 14, in list
    queryset = Head_content.objects.filter({"is_in_serving":1})
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1350, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1381, in _add_q
    check_filterable=check_filterable,
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1236, in build_filter
    raise FieldError("Cannot parse keyword query as dict")
django.core.exceptions.FieldError: Cannot parse keyword query as dict
[2020-11-08 09:30:45,158] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 500 133184
[2020-11-08 09:30:49,352] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /head_content/head/
Traceback (most recent call last):
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\djangos\mysite\apps\head_tabar\views.py", line 14, in list
    queryset = Head_content.objects.filter({"is_in_serving":1})
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1350, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1381, in _add_q
    check_filterable=check_filterable,
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1236, in build_filter
    raise FieldError("Cannot parse keyword query as dict")
django.core.exceptions.FieldError: Cannot parse keyword query as dict
[2020-11-08 09:30:49,357] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 500 133184
[2020-11-08 09:31:01,164] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 09:31:02,366] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:31:09,633] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 09:31:10,807] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:31:12,730] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /head_content/head/
Traceback (most recent call last):
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\djangos\mysite\apps\head_tabar\views.py", line 14, in list
    queryset = Head_content.objects.filter({"is_in_serving":1})
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\query.py", line 904, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\query.py", line 923, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1350, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1381, in _add_q
    check_filterable=check_filterable,
  File "D:\20190930\envs\my_env\lib\site-packages\django\db\models\sql\query.py", line 1236, in build_filter
    raise FieldError("Cannot parse keyword query as dict")
django.core.exceptions.FieldError: Cannot parse keyword query as dict
[2020-11-08 09:31:12,738] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 500 133165
[2020-11-08 09:31:53,835] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 09:31:55,096] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:31:57,321] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /head_content/head/
Traceback (most recent call last):
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\djangos\mysite\apps\head_tabar\views.py", line 15, in list
    for i in queryset[0]:
TypeError: 'Head_content' object is not iterable
[2020-11-08 09:31:57,325] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 500 103513
[2020-11-08 09:31:57,369] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-11-08 09:32:02,313] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /head_content/head/
Traceback (most recent call last):
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\djangos\mysite\apps\head_tabar\views.py", line 15, in list
    for i in queryset[0]:
TypeError: 'Head_content' object is not iterable
[2020-11-08 09:32:02,315] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 500 103513
[2020-11-08 09:32:13,301] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 09:32:14,502] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:32:16,207] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 200 24925
[2020-11-08 09:32:16,239] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[2020-11-08 09:32:16,240] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[2020-11-08 09:32:16,245] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 09:32:16,246] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[2020-11-08 09:32:16,246] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 09:32:16,248] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[2020-11-08 09:43:37,148] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:44:38,652] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:55:15,908] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:55:22,374] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /head_content/head/
Traceback (most recent call last):
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\djangos\mysite\apps\head_tabar\views.py", line 16, in list
    return Response(serializer.data)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\serializers.py", line 745, in data
    ret = super().data
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\serializers.py", line 664, in to_representation
    self.child.to_representation(item) for item in iterable
TypeError: 'Head_content' object is not iterable
[2020-11-08 09:55:22,379] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /head_content/head/?type=guess&geohash=28.227779%2C112.938858 HTTP/1.1" 500 20255
[2020-11-08 09:55:40,536] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 09:55:41,792] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:55:44,316] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?type=guess&geohash=28.227779%2C112.938858 HTTP/1.1" 200 667
[2020-11-08 09:56:06,656] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 09:56:07,928] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:56:09,147] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?type=guess&geohash=28.227779%2C112.938858 HTTP/1.1" 200 10719
[2020-11-08 09:56:41,651] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 09:56:42,968] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:56:45,007] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?type=guess&geohash=28.227779%2C112.938858 HTTP/1.1" 200 10719
[2020-11-08 09:57:32,383] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 09:57:33,905] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 09:57:58,893] [log.py:228] [log:log_response] [WARNING]- Not Found: //app/v1/map/city/
[2020-11-08 09:57:58,893] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET //app/v1/map/city/ HTTP/1.1" 404 2312
[2020-11-08 09:57:58,933] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-11-08 09:57:58,933] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2294
[2020-11-08 09:58:59,210] [views.py:95] [views:list] [ERROR]- 参数错误
[2020-11-08 09:58:59,231] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /app/v1/map/city/ HTTP/1.1" 200 10099
[2020-11-08 09:58:59,268] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[2020-11-08 09:58:59,269] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[2020-11-08 09:58:59,272] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[2020-11-08 09:58:59,275] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[2020-11-08 09:58:59,275] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[2020-11-08 09:58:59,277] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[2020-11-08 09:58:59,279] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[2020-11-08 09:58:59,280] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[2020-11-08 09:58:59,282] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[2020-11-08 09:58:59,282] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[2020-11-08 09:58:59,293] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[2020-11-08 10:02:29,606] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:02:37,208] [log.py:228] [log:log_response] [ERROR]- Internal Server Error: /head_content/head/
Traceback (most recent call last):
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'QuerySet' object has no attribute 'is_in_serving'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\20190930\envs\my_env\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "D:\djangos\mysite\apps\head_tabar\views.py", line 17, in list
    return Response(serializer.data)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\serializers.py", line 548, in data
    ret = super().data
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "D:\20190930\envs\my_env\lib\site-packages\rest_framework\fields.py", line 490, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `is_in_serving` on serializer `HeadContentSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `QuerySet` instance.
Original exception text was: 'QuerySet' object has no attribute 'is_in_serving'.
[2020-11-08 10:02:37,213] [basehttp.py:157] [basehttp:log_message] [ERROR]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 500 138331
[2020-11-08 10:02:46,409] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 10:02:47,627] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:02:48,555] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 200 24925
[2020-11-08 10:02:48,584] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2020-11-08 10:02:48,592] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2020-11-08 10:02:48,593] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2020-11-08 10:02:48,593] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-11-08 10:02:48,594] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 10:02:48,594] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 10:03:05,477] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 10:03:06,682] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:03:07,683] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 200 24925
[2020-11-08 10:03:07,710] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2020-11-08 10:03:07,710] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2020-11-08 10:03:07,710] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2020-11-08 10:03:07,716] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 10:03:07,717] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-11-08 10:03:07,717] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 10:03:07,758] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-11-08 10:03:14,219] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 200 24925
[2020-11-08 10:03:14,250] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2020-11-08 10:03:14,250] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2020-11-08 10:03:14,251] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 10:03:14,252] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2020-11-08 10:03:14,253] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 10:03:14,253] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-11-08 10:03:14,307] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-11-08 10:03:25,522] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:03:29,499] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 200 24925
[2020-11-08 10:03:29,530] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2020-11-08 10:03:29,539] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 10:03:29,540] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2020-11-08 10:03:29,541] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2020-11-08 10:03:29,543] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-11-08 10:03:29,545] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 10:03:29,581] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-11-08 10:03:51,339] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 10:03:52,509] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:03:54,368] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 200 24925
[2020-11-08 10:03:54,393] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2020-11-08 10:03:54,403] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2020-11-08 10:03:54,406] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 10:03:54,406] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 10:03:54,407] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-11-08 10:03:54,407] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2020-11-08 10:03:54,447] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-11-08 10:04:29,780] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 10:04:30,948] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:04:36,968] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 10:04:38,129] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:04:39,260] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 200 25595
[2020-11-08 10:04:39,281] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2020-11-08 10:04:39,284] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2020-11-08 10:04:39,290] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 10:04:39,290] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2020-11-08 10:04:39,291] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-11-08 10:04:39,291] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 10:04:39,331] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-11-08 10:06:28,317] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:06:30,486] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 10:06:31,809] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:12:14,003] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:12:17,272] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 200 24925
[2020-11-08 10:12:17,304] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[2020-11-08 10:12:17,315] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[2020-11-08 10:12:17,316] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[2020-11-08 10:12:17,316] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[2020-11-08 10:12:17,317] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[2020-11-08 10:12:17,320] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[2020-11-08 10:12:17,324] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[2020-11-08 10:12:17,325] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[2020-11-08 10:12:17,327] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[2020-11-08 10:12:17,330] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[2020-11-08 10:12:17,350] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[2020-11-08 10:12:17,399] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-11-08 10:12:17,401] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2294
[2020-11-08 10:12:40,989] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 10:12:42,172] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:12:43,500] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 200 24925
[2020-11-08 10:12:43,543] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2020-11-08 10:12:43,544] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2020-11-08 10:12:43,544] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-11-08 10:12:43,544] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2020-11-08 10:12:43,545] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 10:12:43,545] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 10:13:20,754] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 10:13:21,934] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:13:24,770] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 200 24925
[2020-11-08 10:13:24,797] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2020-11-08 10:13:24,805] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-11-08 10:13:24,805] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2020-11-08 10:13:24,806] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2020-11-08 10:13:24,807] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 10:13:24,808] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 10:14:21,340] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 10:14:22,494] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:14:31,163] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\head_tabar\views.py changed, reloading.
[2020-11-08 10:14:32,336] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:14:34,134] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 200 11139
[2020-11-08 10:14:34,162] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2020-11-08 10:14:34,166] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 10:14:34,177] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2020-11-08 10:14:34,177] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2020-11-08 10:14:34,177] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-11-08 10:14:34,178] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 10:22:03,251] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:22:25,670] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:22:26,682] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /head_content/head/?geohash=&group_type=1&flags[]=F HTTP/1.1" 200 24925
[2020-11-08 10:22:26,699] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[2020-11-08 10:22:26,702] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[2020-11-08 10:22:26,705] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[2020-11-08 10:22:26,705] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[2020-11-08 10:22:26,706] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[2020-11-08 10:22:26,707] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[2020-11-08 10:22:36,166] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:29:58,706] [views.py:174] [views:guessPosition] [ERROR]- 获取位置信息错误
[2020-11-08 10:29:58,706] [views.py:235] [views:get_city_name] [ERROR]- 'NoneType' object is not iterable
[2020-11-08 10:57:03,985] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 10:57:33,934] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 10:57:33,935] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2295
[2020-11-08 10:57:38,119] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 10:57:38,119] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2295
[2020-11-08 10:58:13,975] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 10:58:13,975] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2295
[2020-11-08 11:07:12,528] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 11:07:15,137] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 11:07:15,138] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2295
[2020-11-08 11:07:15,140] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/index_entry
[2020-11-08 11:07:15,141] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 404 2343
[2020-11-08 11:07:41,247] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 11:07:41,248] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2295
[2020-11-08 11:07:41,258] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/index_entry
[2020-11-08 11:07:41,259] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 404 2343
[2020-11-08 11:08:59,012] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 11:08:59,012] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2295
[2020-11-08 11:08:59,014] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/index_entry
[2020-11-08 11:08:59,015] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 404 2343
[2020-11-08 11:10:59,941] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 11:11:04,158] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/index_entry
[2020-11-08 11:11:04,159] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 404 2342
[2020-11-08 11:11:04,160] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 11:11:04,161] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2927
[2020-11-08 11:11:11,281] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 11:11:11,281] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2927
[2020-11-08 11:11:11,284] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/index_entry
[2020-11-08 11:11:11,285] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 404 2342
[2020-11-08 11:14:34,223] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 11:14:34,227] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2927
[2020-11-08 11:14:34,231] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/index_entry
[2020-11-08 11:14:34,232] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 404 2342
[2020-11-08 11:16:18,552] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /v1/map/city/pois/ HTTP/1.1" 200 10186
[2020-11-08 11:16:18,585] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[2020-11-08 11:16:18,592] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[2020-11-08 11:16:18,594] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[2020-11-08 11:16:18,595] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[2020-11-08 11:16:18,596] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[2020-11-08 11:16:18,600] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[2020-11-08 11:16:18,600] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[2020-11-08 11:16:18,602] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[2020-11-08 11:16:18,603] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[2020-11-08 11:16:18,606] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[2020-11-08 11:16:18,618] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[2020-11-08 11:16:18,654] [log.py:228] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2020-11-08 11:16:18,656] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 2293
[2020-11-08 11:17:48,966] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/index_entry
[2020-11-08 11:17:48,967] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 11:17:48,967] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 404 2342
[2020-11-08 11:17:48,968] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2927
[2020-11-08 11:30:47,191] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 12:17:28,971] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 12:17:28,972] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/index_entry
[2020-11-08 12:17:28,972] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2927
[2020-11-08 12:17:28,973] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 404 2342
[2020-11-08 14:53:44,700] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/pois/undefined,undefined
[2020-11-08 14:53:44,702] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/pois/undefined,undefined HTTP/1.1" 404 2341
[2020-11-08 14:53:44,712] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 14:53:44,713] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2927
[2020-11-08 14:53:44,861] [log.py:228] [log:log_response] [WARNING]- Not Found: /shopping/restaurants
[2020-11-08 14:53:44,863] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/index_entry
[2020-11-08 14:53:44,863] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /shopping/restaurants?latitude=undefined&longitude=undefined&offset=0&limit=20&extras[]=activities&keyword=&restaurant_category_id=&restaurant_category_ids[]=&order_by=&delivery_mode[]= HTTP/1.1" 404 2520
[2020-11-08 14:53:44,864] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/index_entry?geohash=undefined,undefined&group_type=1&flags[]=F HTTP/1.1" 404 2361
[2020-11-08 14:54:41,566] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/pois/undefined,undefined
[2020-11-08 14:54:41,566] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/pois/undefined,undefined HTTP/1.1" 404 2341
[2020-11-08 14:54:41,594] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 14:54:41,595] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2927
[2020-11-08 14:54:41,683] [log.py:228] [log:log_response] [WARNING]- Not Found: /shopping/restaurants
[2020-11-08 14:54:41,684] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /shopping/restaurants?latitude=undefined&longitude=undefined&offset=0&limit=20&extras[]=activities&keyword=&restaurant_category_id=&restaurant_category_ids[]=&order_by=&delivery_mode[]= HTTP/1.1" 404 2520
[2020-11-08 14:54:41,722] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/index_entry
[2020-11-08 14:54:41,723] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/index_entry?geohash=undefined,undefined&group_type=1&flags[]=F HTTP/1.1" 404 2361
[2020-11-08 14:54:53,344] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/pois/undefined,undefined
[2020-11-08 14:54:53,344] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/pois/undefined,undefined HTTP/1.1" 404 2341
[2020-11-08 14:54:53,617] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 14:54:53,618] [log.py:228] [log:log_response] [WARNING]- Not Found: /shopping/restaurants
[2020-11-08 14:54:53,620] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/index_entry
[2020-11-08 14:54:53,621] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2927
[2020-11-08 14:54:53,621] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /shopping/restaurants?latitude=undefined&longitude=undefined&offset=0&limit=20&extras[]=activities&keyword=&restaurant_category_id=&restaurant_category_ids[]=&order_by=&delivery_mode[]= HTTP/1.1" 404 2520
[2020-11-08 14:54:53,621] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/index_entry?geohash=undefined,undefined&group_type=1&flags[]=F HTTP/1.1" 404 2361
[2020-11-08 14:55:13,850] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/cities
[2020-11-08 14:55:13,851] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/cities?type=guess HTTP/1.1" 404 2931
[2020-11-08 14:55:13,870] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/index_entry
[2020-11-08 14:55:13,871] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 404 2342
[2020-11-08 14:56:19,661] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/cities
[2020-11-08 14:56:19,669] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 14:56:19,669] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/cities?type=guess HTTP/1.1" 404 2931
[2020-11-08 14:56:19,672] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2927
[2020-11-08 14:56:19,696] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/index_entry
[2020-11-08 14:56:19,700] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 404 2342
[2020-11-08 14:58:07,751] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\v1\urls.py changed, reloading.
[2020-11-08 14:58:09,113] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 14:58:13,055] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /v1/cities?type=guess HTTP/1.1" 301 0
[2020-11-08 14:58:13,299] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 14:58:13,301] [log.py:228] [log:log_response] [WARNING]- Not Found: /v2/index_entry
[2020-11-08 14:58:13,302] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2925
[2020-11-08 14:58:13,302] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v2/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 404 2342
[2020-11-08 14:59:22,128] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 14:59:52,980] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\v2\urls.py changed, reloading.
[2020-11-08 14:59:54,144] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 15:01:31,176] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 15:02:23,273] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 15:02:30,380] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /v1/cities?type=guess HTTP/1.1" 301 0
[2020-11-08 15:02:30,393] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /v2/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 301 0
[2020-11-08 15:02:30,403] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 15:02:30,404] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2915
[2020-11-08 15:04:36,534] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 15:04:44,955] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /v1/cities?type=guess HTTP/1.1" 301 0
[2020-11-08 15:04:44,987] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /v2/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 301 0
[2020-11-08 15:04:44,996] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 15:04:44,997] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2906
[2020-11-08 15:58:50,342] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 15:59:25,559] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /v1/cities?type=guess HTTP/1.1" 301 0
[2020-11-08 15:59:25,603] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 15:59:25,604] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2906
[2020-11-08 15:59:31,878] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 15:59:39,917] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /v1/cities?type=guess HTTP/1.1" 301 0
[2020-11-08 15:59:39,959] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 15:59:39,960] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2906
[2020-11-08 16:00:38,580] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 16:00:40,521] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /v1/cities?type=guess HTTP/1.1" 301 0
[2020-11-08 16:00:40,734] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 16:00:40,735] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2906
[2020-11-08 16:00:40,833] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /v3/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 301 0
[2020-11-08 16:00:54,435] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 16:01:42,215] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /v1/cities?type=guess HTTP/1.1" 301 0
[2020-11-08 16:01:42,254] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 16:01:42,256] [log.py:228] [log:log_response] [WARNING]- Not Found: /v3/index_entry
[2020-11-08 16:01:42,256] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2906
[2020-11-08 16:01:42,257] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v3/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 404 2332
[2020-11-08 16:02:33,594] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 16:03:34,857] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /v1/cities?type=guess HTTP/1.1" 301 0
[2020-11-08 16:03:34,882] [basehttp.py:157] [basehttp:log_message] [INFO]- "GET /v2/index_entry?geohash=&group_type=1&flags[]=F HTTP/1.1" 301 0
[2020-11-08 16:03:34,893] [log.py:228] [log:log_response] [WARNING]- Not Found: /v1/user
[2020-11-08 16:03:34,894] [basehttp.py:157] [basehttp:log_message] [WARNING]- "GET /v1/user?user_id=null HTTP/1.1" 404 2906
[2020-11-08 20:17:38,771] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 20:18:04,181] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\mysite\settings.py changed, reloading.
[2020-11-08 20:18:05,776] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 20:48:05,764] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 20:56:16,818] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\v1\urls.py changed, reloading.
[2020-11-08 20:56:18,393] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 20:58:31,311] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\v1\views.py changed, reloading.
[2020-11-08 20:58:33,256] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 20:59:13,386] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\v1\views.py changed, reloading.
[2020-11-08 20:59:15,075] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 20:59:29,906] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\v1\views.py changed, reloading.
[2020-11-08 20:59:31,456] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 21:01:20,134] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\v1\views.py changed, reloading.
[2020-11-08 21:01:21,604] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2020-11-08 21:02:17,435] [autoreload.py:222] [autoreload:trigger_reload] [INFO]- D:\djangos\mysite\apps\v1\views.py changed, reloading.
[2020-11-08 21:02:19,115] [autoreload.py:598] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
